spring:
  application:
    name: "luggage-service"


database:
  host: localhost
  port: 54322
  name: easyFly
  username: luggage_user
  password: Yaman.1903

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/

luggage-system:
    notification-api:
        baseUrl: http://localhost:8084
        connectTimeout: 5000ms
        readTimeout: 10000ms
    customer-api:
        baseUrl: http://localhost:8081
        connectTimeout: 5000ms
        readTimeout: 10000ms


server:
  port: 7074
