spring:
  application:
    name: "luggage-service"
  kafka:
    bootstrap-servers: http://localhost:29092
    consumer:
       auto-offset-reset: earliest
       group-id: kafka-consumer
    producer:
       key-serializer: org.apache.kafka.common.serialization.StringSerializer
       value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


database:
  host: localhost
  port: 5432
  name: easyFly
  username: postgres
  password: 1212anan

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/

luggage-system:
    notification-api:
        baseUrl: http://localhost:8084
        connectTimeout: 5000ms
        readTimeout: 10000ms
    customer-api:
        baseUrl: http://localhost:8081
        connectTimeout: 5000ms
        readTimeout: 10000ms


server:
  port: 7074
