spring:
  application:
    name: "luggage-service"
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: luggages
  datasource:
    username: ${DATASOURCE_USERNAME:luggage_user}
    password: ${DATASOURCE_PASSWORD:Yaman.1903}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54322/easyFly}
  flyway:
    enabled: true
    validate-on-migrate: true
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54322/easyFly}
    default-schema: luggages
    user: ${DATASOURCE_USERNAME:luggage_user}
    password: ${DATASOURCE_PASSWORD:Yaman.1903}


server:
  port: 7074
